version: "3.8"

services:
  backend:
    build:
      context: ./server
    container_name: django-backend
    volumes:
      - ./server:/app
      - ./server/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver_plus 0.0.0.0:8000 --cert-file ./ssl/server.crt --key-file ./ssl/server.key"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      retries: 3

  frontend:
    build:
      context: ./client
    container_name: nextjs-frontend
    volumes:
      - ./client:/app
      - node_modules:/app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  node_modules:

