services:
  backend:
    build:
      context: ./server
    container_name: django-backend
    env_file:
      - .env
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      retries: 3
  frontend:
    build:
      context: ./client
    container_name: nextjs-frontend
    env_file:
      - .env
    volumes:
      - ./client:/app
    ports:
      - "3001:3000"
    depends_on:
      - backend

  
