# Generated by Django 5.1.4 on 2025-01-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Regular User', 'Regular User'), ('Guest', 'Guest')], default='Regular User', max_length=20),
        ),
    ]
